name: Deploy to Live

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch, tag or commit to deploy"
        required: true
        default: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Configure SSH
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.TM_STORE_PASS }}" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
            ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Live
        run: |
          DEST="${{ secrets.TM_STORE_SSH_USER }}@${{ secrets.SSH_HOST }}:${{ vars.LIVE_DEPLOY_PATH }}"
          SSH="ssh -i ~/.ssh/id_ed25519"

          rsync -azc --omit-dir-times --no-times --no-perms --no-owner --no-group -e "$SSH" ./assets/ "$DEST/assets/"
          rsync -azc --omit-dir-times --no-times --no-perms --no-owner --no-group -e "$SSH" ./src/ "$DEST/src/"
          rsync -azc --omit-dir-times --no-times --no-perms --no-owner --no-group -e "$SSH" ./tm-three-viewer.php "$DEST/tm-three-viewer.php"

      - name: Complete
        run: echo "Live deployment complete."