name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TM_STORE_PASS }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.TM_STORE_SSH_USER }}@${{ secrets.SSH_HOST }} \
          "whoami && ls -la ${{ secrets.TM_STORE_STAGING_PATH }}"